USE [NanJingEdu]
GO

/****** Object:  StoredProcedure [dbo].[PAGING_COMMON]    Script Date: 11/24/2014 13:58:59 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROC [dbo].[PAGING_COMMON](
	@TABLE_NAME VARCHAR(50), -- 表名
	@FIELDS VARCHAR(300), -- 字段,可以为*
	@PAGE_INDEX INT, -- 当前页码,默认从1开始,不是0
	@PAGE_SIZE INT, -- 一页显示的记录数
	@WHERE VARCHAR(300), -- 查询条件
	@ORDER_BY VARCHAR(100), -- 排序
	@TOTAL INT OUT	--输出参数 总记录数
)
AS
SET NOCOUNT ON;

IF @PAGE_INDEX<=0 OR @PAGE_SIZE<=0
RETURN -1; -- 未执行标识
IF RTRIM(LTRIM(@ORDER_BY)) ='' OR @ORDER_BY IS NULL
RETURN -1; -- 未执行标识

IF RTRIM(LTRIM(@WHERE)) ='' OR @WHERE IS NULL
SET @WHERE='1=1';
--获取记录
DECLARE @SQL NVARCHAR(3000);
DECLARE @START_INDEX INT;
SET @START_INDEX=(@PAGE_INDEX-1)*@PAGE_SIZE;
DECLARE @TOP_ROW_NUM INT;
SET @TOP_ROW_NUM=@PAGE_INDEX*@PAGE_SIZE;
SET @SQL='SELECT TOP '+CAST(@PAGE_SIZE AS VARCHAR)+' '+@FIELDS+' FROM 
			(
			 SELECT TOP '+CAST(@TOP_ROW_NUM AS VARCHAR)+' ROW_NUMBER() OVER (ORDER BY '+@ORDER_BY+')				AS RID,* FROM '+@TABLE_NAME+'  WHERE '+@WHERE+' ORDER BY RID
			)
		  AS T WHERE T.RID > '+CAST(@START_INDEX AS VARCHAR)+' ORDER BY T.RID';
--获取记录条数
DECLARE @COUNT_SQL NVARCHAR(3000);
SET @COUNT_SQL='SELECT @TOTAL=COUNT(1) FROM '+@TABLE_NAME+' WHERE '+@WHERE+'';

EXEC SP_EXECUTESQL @COUNT_SQL,N'@TOTAL INT OUT',@TOTAL OUT
EXEC SP_EXECUTESQL @SQL

return 1 -- 执行成功标识








GO


